### ISSUE TITLE
Enforce HTTPS server-side

### ISSUE THREAD

**Issue by konklone** [emanuelfeld/emanuelfeld.github.io#2]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS without errors: https://emanuelfeld.github.io So this should be a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by emanuelfeld** [comment]
Thanks, done!

**Comment by konklone** [comment]
Awesome, thanks!
